---
- name: Playbook packager.yml
  hosts: linux
  become: yes

  tasks:
  - name: Installiere git-all
    yum: 
      name: "{{ item }}"
      state: absent
    loop:
     - git-all
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

