---
- name: Playbook users_info.yml
  hosts: all
  become: yes
#  gather_facts: False
#  vars:
#    userlist: 
#      - root
#      - playbookvar

  tasks:
  - name: Speichere die gefundenen Benutzer in existing_users
    shell: 'cut -d: -f1 /etc/passwd | tr "," "\n"'
    changed_when: false 
    register: existing_users

  - name: Zeige die Benutzer aus existing_users
    debug:
      var: existing_users.stdout_lines

  - name: Check for listed users
    loop: "{{ userlist }}"
    changed_when: false
    command: grep {{ item }} -q /etc/passwd
    when: userlist is defined
    ignore_errors: yes
